export const UNIVERSITIES = [
  "Arizona State University",
  "Boston University",
  "Brown University",
  "California Institute of Technology",
  "Carnegie Mellon University",
  "Columbia University",
  "Cornell University",
  "Duke University",
  "Emory University",
  "Georgetown University",
  "Georgia Institute of Technology",
  "Harvard University",
  "Johns Hopkins University",
  "Massachusetts Institute of Technology",
  "Michigan State University",
  "New York University",
  "Northeastern University",
  "Northwestern University",
  "Ohio State University",
  "Pennsylvania State University",
  "Princeton University",
  "Purdue University",
  "Rice University",
  "Stanford University",
  "Texas A&M University",
  "Tufts University",
  "University of California, Berkeley",
  "University of California, Los Angeles",
  "University of California, San Diego",
  "University of Chicago",
  "University of Florida",
  "University of Illinois Urbana-Champaign",
  "University of Maryland",
  "University of Michigan",
  "University of Minnesota",
  "University of North Carolina at Chapel Hill",
  "University of Notre Dame",
  "University of Pennsylvania",
  "University of Southern California",
  "University of Texas at Austin",
  "University of Virginia",
  "University of Washington",
  "University of Wisconsin-Madison",
  "Vanderbilt University",
  "Washington University in St. Louis",
  "Yale University",
] as const;
